import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import "dotenv/config";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const pluginDir = process.env.OBSIDIAN_PLUGIN_DIR || ".";
const outfile = `${pluginDir}/main.js`;


esbuild
    .build({
        banner: {
            js: banner,
        },
        entryPoints: ["src/main.ts"],
        bundle: true,
        external: ["obsidian", "electron", ...builtins],
        format: "cjs",
        watch: !prod,
        target: "es2016",
        logLevel: "info",
        sourcemap: "inline",
        sourcesContent: !prod,
        treeShaking: true,
        outfile,
    })
    .catch(() => process.exit(1));
